SELECT gender, 
	SUM(CASE WHEN outcome = 'ACTIVE' THEN 1 ELSE 0 END) AS "ACTIVE",
	SUM(CASE WHEN outcome = 'RESOLVED' THEN 1 ELSE 0 END) AS "RESOLVED",
	SUM(CASE WHEN outcome = 'FATAL' THEN 1 ELSE 0 END) AS "FATAL",
	ROUND(SUM(CASE WHEN outcome = 'ACTIVE' THEN 1.0 ELSE 0.0 END)/COUNT(*)*100,2) AS "Percentage ACTIVE",
	ROUND(SUM(CASE WHEN outcome = 'RESOLVED' THEN 1.0 ELSE 0.0 END)/COUNT(*)*100,2) AS "Percentage RESOLVED",
	ROUND(SUM(CASE WHEN outcome = 'FATAL' THEN 1.0 ELSE 0.0 END)/COUNT(*)*100,2) AS "Percentage FATAL"

FROM "Toronto_Cases"
GROUP BY gender
ORDER BY gender